### ISSUE TITLE
When using history incorrect arguments may be sent

### ISSUE THREAD

**Issue by fundamental** [fundamental/oscprompt#6]
I'm guessing the argument parser isn't called when changing between history items which may result with a stale message argument type string.

**Comment by JohannesLorenz** [comment]
I could reproduce the bug:
```
/float 1.0
/int 2 3
<retype first call by using history>
```
oscdump says:
```
/float f 1.000000
/int ii 2 3
/float fi 1.000000 50331648
```

**Comment by JohannesLorenz** [comment]
When browsing back in the history, the arguments are parsed correctly from the `message_buffer`, but a final 0-termination is missing. I just tried to add
```C++
message_arguments[message_narguments] = 0;
```
behind the while loop from `print_colorized_message` ( https://github.com/fundamental/oscprompt/blob/master/render.cpp#L242 ) and it fixed the bug shown above.

Is this the only bug you had? I ask because you had a solution with calling `rebuild_status` in mind?

**Comment by fundamental** [comment]
That would seem to be the full bug for this issue. I know there is some other weirdness when navigating multiple history entries, but I'd say that should be covered by a separate bug report/fix.
